In [1]:
from alpha_vantage.timeseries import TimeSeries
from pprint import pprint
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
ts = TimeSeries(key='X5AYBIDIH2EVGNW9', output_format='pandas')
data, meta_data = ts.get_daily(symbol='TSLA', outputsize='full')

data = data.drop(['2. high', '3. low', '5. volume'], axis=1)
data.columns = ['open', 'close']

In [23]:
def calculate_pct_change(open, close):
    pct_change = (close - open) / open
    pct_change = round(pct_change,4) * 100
    return pct_change

In [24]:
#S&P 500 data
sdata, smeta_data = ts.get_daily(symbol='SPY', outputsize='full')

sdata = sdata.drop(['2. high', '3. low', '5. volume'], axis=1)
sdata.columns = ['open', 'close']

In [25]:
data = calculate_pct_change(data.open, data.close) - calculate_pct_change(sdata.open, sdata.close)
data = pd.DataFrame({'Date': data.index, 'price_change': data.values})
data = data.set_index('Date')
data["signal"] = data['price_change'].map(lambda x: "stay" if -1<x<1 else ("up" if x>1 else "down"))
data = data.drop(['price_change'], axis = 1)

In [46]:
data = data.loc[(data.index > '2012-11-16') & ('2017-09-29' >= data.index)]

In [47]:
data['signal'].value_counts()

stay    504
down    374
up      347
Name: signal, dtype: int64

In [48]:
data

           signal
Date
2012-11-19     up
2012-11-20   stay
2012-11-21   stay
2012-11-23   down
2012-11-26   stay
2012-11-27   stay
2012-11-28     up
2012-11-29   stay
2012-11-30   stay
2012-12-03     up
2012-12-04   stay
2012-12-05   stay
2012-12-06   stay
2012-12-07   stay
2012-12-10   stay
2012-12-11     up
2012-12-12   stay
2012-12-13   down
2012-12-14   stay
2012-12-17   stay
2012-12-18   stay
2012-12-19   stay
2012-12-20   stay
2012-12-21   stay
2012-12-24     up
2012-12-26   stay
2012-12-27   stay
2012-12-28   stay
2012-12-31   stay
2013-01-02   stay
...           ...
2017-08-18   down
2017-08-21   down
2017-08-22   stay
2017-08-23     up
2017-08-24   stay
2017-08-25   down
2017-08-28   stay
2017-08-29     up
2017-08-30   stay
2017-08-31   stay
2017-09-01   stay
2017-09-05   stay
2017-09-06   down
2017-09-07     up
2017-09-08   down
2017-09-11     up
2017-09-12   stay
2017-09-13   stay
2017-09-14     up
2017-09-15     up
2017-09-18     up
2017-09-19   down
2017-09-20   stay
2017-09-21   down
2017-09-22   down
2017-09-25   down
2017-09-26   down
2017-09-27   down
2017-09-28   stay
2017-09-29   stay

[1225 rows x 1 columns]